repos:
  # --- Base standard hooks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  # --- Black: auto-formatting ---
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        additional_dependencies: [click]
        language_version: python3.11

  # --- Ruff: linter and auto-fix ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]

  # --- Mypy: type checking ---
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        pass_filenames: false
        args:
          - --strict
          - --ignore-missing-imports
          - --explicit-package-bases
          - -p
          - opmed          # check package by name, not src folder
        additional_dependencies:
          - pydantic
          - pandas
          - pyyaml
          - matplotlib
          - ortools
